### ISSUE TITLE
Can not use French language for report generation

### ISSUE THREAD

**Issue by sebcaps** [jan-molak/serenity-cli-node#4]
Using the following feature file

```
# encoding: utf8
# language: fr 

Fonctionnalité: Log in

  Pour se connecter
  En tant que la bonne personne
  Je veux être capable de me connecter
  
  Scénario: Ne me connecte pas

  Soit George Rémy est un utilisateur
  Etant donné qu'elle essaye de se connecter avec l'identifiant not@acme.com et le mot de passe auser
  Alors il est n'est pas connecté
```

 I can run serernity-js test but when generating report I got the following error ```info: Writing aggregated report to C:\Users\sebcc\Documents\serenity-tests\target\site\serenity
error: Exception in thread "pool-1-thread-2" gherkin.lexer.LexingError: Lexing error on line 1: 'Fonctionnalité: Log in
An error occurred. Error: Exception in thread "pool-1-thread-2" gherkin.lexer.LexingError: Lexing error on line 1: 'Fonctionnalité: Log in
    at C:\Users\sebcc\Documents\serenity-tests\node_modules\serenity-cli\lib\actions\logging.js:8:35
    at process._tickCallback (internal/process/next_tick.js:109:7)` and no report generated.```

When removing #encoding, # language et renaming Fonctionnalité to Feature, report generation is OK.

**Comment by jan-molak** [comment]
Looks like something in https://github.com/serenity-bdd/serenity-cli?
@wakaleo?

**Comment by jan-molak** [comment]
Hi @sebcaps, could you please check if the latest version solves the problem for you?

Thanks,
Jan

**Comment by sebcaps** [comment]
Unfortunately no improvements with the latest version.

**Comment by jan-molak** [comment]
Needs more investigation, potentially related: serenity-bdd/serenity-core#793
