### ISSUE TITLE
Error when calling serenity

### ISSUE THREAD

**Issue by dpkano** [jan-molak/serenity-cli-node#9]
Hi,
    I've just updated my serenity-cli (to 0.5.0) and I started getting this:

$ ./node_modules/.bin/serenity update
module.js:471
    throw err;
    ^

Error: Cannot find module 'address'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ($dir\node_modules\detect-port\lib\detect-port.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by dpkano** [comment]
0.6.0 fixes it. Thanks.
